// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4VyLVep3l0OXbTmXZ4--48oJFtFhZmkM',
    appId: '1:670314008187:android:70c9cb4012541753271cde',
    messagingSenderId: '670314008187',
    projectId: 'chatapptask-5b63d',
    storageBucket: 'chatapptask-5b63d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJkj3QHLhcfelv8ZhTUQczZNkBdbwYxr8',
    appId: '1:670314008187:ios:8403fda252eb89e5271cde',
    messagingSenderId: '670314008187',
    projectId: 'chatapptask-5b63d',
    storageBucket: 'chatapptask-5b63d.appspot.com',
    iosBundleId: 'com.example.chatAppTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOmOtBxTV1-qao6uBm0g76v0RdzRznKRY',
    appId: '1:670314008187:web:c3fdcd13d519853e271cde',
    messagingSenderId: '670314008187',
    projectId: 'chatapptask-5b63d',
    authDomain: 'chatapptask-5b63d.firebaseapp.com',
    storageBucket: 'chatapptask-5b63d.appspot.com',
    measurementId: 'G-NHY5BNB89W',
  );
}
